---

- name: Adicionando chave gpg do K8S
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: instala o repo do k8s
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: kubernetes.list

- name: Instalação do kubernetes
  ansible.builtin.apt:
    pkg:
      - "kubeadm={{ k8s_version }}"
      - "kubectl={{ k8s_version }}"
    state: present
    update_cache: yes

- name: Configuração do hold dos pacotes
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubectl

- name: Configuração de SSH solicitada para RKE
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    line: "AllowTcpForwarding yes"
    backup: yes

- name: Criando usuário do RKE para criação do cluster
  ansible.builtin.user:
    name: k8s
    groups: docker
    generate_ssh_key: yes
    shell: /bin/bash
    state: present

- name: Aplicando a chave publica do usuário k8s
  ansible.builtin.authorized_key:
    user: k8s
    state: present
    key: https://github.com/mentoriaiacuser.keys
